name: Update Resume Section

on:
  workflow_dispatch:
    inputs:
      section:
        description: 'Section to update (example: experience)'
        required: true
      new_content:
        description: 'New LaTeX resumeItem lines to insert'
        required: true

jobs:
  update-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Replace Section Content
        run: |
          FILE="src/${{ github.event.inputs.section }}.tex"

          echo 'import re

            file_path = "'"$FILE"'"
            new_content = """${{ github.event.inputs.new_content }}"""

            with open(file_path, "r") as f:
                content = f.read()

            # Find all occurrences
            matches = list(re.finditer(r"(\\\\resumeItemListStart\\n)(.*?)(\\\\resumeItemListEnd)", content, flags=re.DOTALL))

            if matches:
                # Just update the first block for now (or adjust if needed)
                match = matches[0]
                updated = content[:match.start(2)] + new_content + content[match.end(2):]

                with open(file_path, "w") as f:
                    f.write(updated)
            else:
                print("No matching block found!")
            ' > replace.py

                    python3 replace.py

                    - name: Commit and Push Changes
                    env:
                      PAT: ${{ secrets.GH_PAT }}
                    run: |
                      git config --global user.name 'resume-updater-bot'
                      git config --global user.email 'resume-bot@example.com'
                  
                      git remote set-url origin https://x-access-token:${PAT}@github.com/jayshrivastava0/Latex-Resume.git
                  
                      git add src/${{ github.event.inputs.section }}.tex
                      git commit -m "🔄 Auto-update ${{ github.event.inputs.section }} section"
                      git push origin main
                  
